[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./startup.sh"

# Volume for persistent database storage
[[volumes]]
name = "database_volume"
mountPath = "/app/data"

# Environment variables
[deploy.env]
RAILWAY_RUN_UID = "0"
